language: objective-c
osx_image: xcode10.1
sudo: false

cache: bundler

branches:
    only:
        - master
        - /^feature\/.*$/

env:
    global:
        - LC_CTYPE=en_US.UTF-8
        - LANG=en_US.UTF-8

    # these lines each add a job to the test stage
    matrix:
        - PLATFORM="iOS Simulator" OS=12.1 SDK=iphonesimulator NAME="iPhone 8" TEST_SCHEME="iOS Tests"
        - PLATFORM="iOS Simulator" OS=11.4 SDK=iphonesimulator NAME="iPhone 8" TEST_SCHEME="iOS Tests"
        - PLATFORM="iOS Simulator" OS=10.3 SDK=iphonesimulator NAME="iPhone 8" TEST_SCHEME="iOS Tests"

        - PLATFORM=macOS OS=10.14 SDK="macOS" NAME="" TEST_SCHEME="OS X Tests"
        - PLATFORM=macOS OS=10.13 SDK="macOS" NAME="" TEST_SCHEME="OS X Tests"
        - PLATFORM=macOS OS=10.12 SDK="macOS" NAME="" TEST_SCHEME="OS X Tests"

before_install:
    - gem update --system
    - gem install bundler

after_install:
    - env
    - locale
    - bundle exec pod --version
    - bundle exec xcpretty --version
    - xcodebuild -version

after_script:
    - bundle exec danger

after_success:
    - bash <(curl -s https://codecov.io/bash)

stages:
    - compile_core
    - test
    - compile_demo_apps

script: bash ./Scripts/test.sh

jobs:
    include:
        - stage: compile_core
          script: bash ./Scripts/compile_core.sh

        - stage: compile_demo_apps
          if: env(TRAVIS_PULL_REQUEST) = false
          script: bash ./Scripts/compile_demo_apps.sh
            